// Provisioning kit — pure generators for the files an ar-io-node host needs (Solana era, r82+).
// Podman by house rule; ar-io-node itself is AGPL-3.0 and is run UNMODIFIED as a separate service
// (images from ghcr.io/ar-io) — nothing of it is vendored here.

import { ARIO_PROGRAMS, RECOMMENDED_NODE_WALLET_SOL, MIN_OPERATOR_SOL } from '../constants';
import { getPermawebSettings } from '../settings';

export interface NodeEnvInput {
  fqdn: string;
  operator: string;          // AR_IO_WALLET (Solana pubkey; signs joinNetwork in parsec — never on the host)
  observer: string;          // OBSERVER_WALLET (Solana pubkey; its keypair JSON goes to wallets/observer.json)
  upload?: string;           // SOLANA_UPLOAD wallet (defaults to the observer key)
  solanaRpcUrl?: string;
  startHeight?: number;
  enableEpochCranking?: boolean;
  adminApiKey?: string;
  keyMode?: 'path' | 'inline';   // inline puts base58 secrets in .env — only if the operator insists
  observerSecretBase58?: string;
  uploadSecretBase58?: string;
}

export function generateNodeEnv(i: NodeEnvInput): string {
  const keyMode = i.keyMode ?? 'path';
  if (keyMode === 'inline' && (!i.observerSecretBase58)) throw new Error('inline key mode needs observerSecretBase58');
  if (keyMode === 'path' && (i.observerSecretBase58 || i.uploadSecretBase58)) throw new Error('path key mode must not carry inline secrets');
  const upload = i.upload ?? i.observer;
  const lines = [
    '# ar-io-node .env — generated by parsec permaweb module (Solana era, ar-io-node r82+)',
    `# Host: ${i.fqdn}   Operator (signs in parsec, never on this host): ${i.operator}`,
    'GRAPHQL_HOST=turbo-gateway.com',
    'GRAPHQL_PORT=443',
    `START_HEIGHT=${i.startHeight ?? 1_750_000}`,
    `ARNS_ROOT_HOST=${i.fqdn}`,
    'RUN_OBSERVER=true',
    `AR_IO_WALLET=${i.operator}`,
    `OBSERVER_WALLET=${i.observer}`,
  ];
  if (keyMode === 'path') {
    lines.push('OBSERVER_KEYPAIR_PATH=/app/wallets/observer.json');
    lines.push(upload === i.observer ? 'SOLANA_UPLOAD_KEYPAIR_PATH=/app/wallets/observer.json' : 'SOLANA_UPLOAD_KEYPAIR_PATH=/app/wallets/upload.json');
  } else {
    lines.push(`OBSERVER_PRIVATE_KEY=${i.observerSecretBase58}`);
    lines.push(`SOLANA_UPLOAD_PRIVATE_KEY=${i.uploadSecretBase58 ?? i.observerSecretBase58}`);
  }
  lines.push(
    `SOLANA_RPC_URL=${i.solanaRpcUrl ?? getPermawebSettings().rpcUrl}`,
    `ARIO_CORE_PROGRAM_ID=${ARIO_PROGRAMS.core}`,
    `ARIO_GAR_PROGRAM_ID=${ARIO_PROGRAMS.gar}`,
    `ARIO_ARNS_PROGRAM_ID=${ARIO_PROGRAMS.arns}`,
    `ARIO_ANT_PROGRAM_ID=${ARIO_PROGRAMS.ant}`,
    `ENABLE_EPOCH_CRANKING=${i.enableEpochCranking ? 'true' : 'false'}`,
    `ADMIN_API_KEY=${i.adminApiKey ?? '<generate: openssl rand -hex 16>'}`,
    '# Deleted AO-era vars (do not set): AO_CU_URL NETWORK_AO_CU_URL ANT_AO_CU_URL AO_MU_URL AO_GATEWAY_URL AO_GRAPHQL_URL WALLETS_PATH',
  );
  return lines.join('\n') + '\n';
}

/** podman-compose file: ar.io core + envoy + observer (no parsec service container). */
export function generatePodmanCompose(): string {
  return `# ar.io gateway — podman-compose (ar-io-node images run unmodified; AGPL-3.0 upstream)
# Usage: podman-compose up -d ; podman-compose pull && podman-compose up -d --force-recreate core envoy observer
# NEVER \`podman-compose down -v\` — it wipes the sqlite index and chunk cache.
services:
  core:
    image: ghcr.io/ar-io/ar-io-core:\${ARIO_CORE_TAG:-latest}
    env_file: .env
    volumes:
      - ./data:/app/data:Z
      - ./wallets:/app/wallets:ro,Z
    ports: ["127.0.0.1:4000:4000"]
    restart: unless-stopped
  envoy:
    image: ghcr.io/ar-io/ar-io-envoy:\${ARIO_ENVOY_TAG:-latest}
    env_file: .env
    environment:
      - TVAL_AR_IO_HOST=core
      - TVAL_AR_IO_PORT=4000
      - TVAL_GATEWAY_HOST=arweave.net
    ports: ["127.0.0.1:3000:3000"]
    depends_on: [core]
    restart: unless-stopped
  observer:
    image: ghcr.io/ar-io/ar-io-observer:\${ARIO_OBSERVER_TAG:-latest}
    env_file: .env
    volumes:
      - ./data:/app/data:Z
      - ./wallets:/app/wallets:ro,Z
    depends_on: [core]
    restart: unless-stopped
`;
}

export function generateNginx(fqdn: string): string {
  return `# nginx — TLS termination for ${fqdn} and *.${fqdn} → envoy :3000
server {
  listen 80;
  server_name ${fqdn} *.${fqdn};
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl http2;
  server_name ${fqdn} *.${fqdn};
  ssl_certificate     /etc/letsencrypt/live/${fqdn}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${fqdn}/privkey.pem;
  client_max_body_size 0;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_http_version 1.1;
    proxy_read_timeout 3600;
  }
}
`;
}

export function generateChecklist(i: NodeEnvInput): string {
  return `AR.IO GATEWAY — ${i.fqdn} — provisioning checklist (Solana era, ar-io-node r82+)

HARDWARE   min 4 cores / 4 GB RAM / 500 GB SSD (ext4) / 50 Mbps — recommended 12 cores / 32 GB / 2 TB NVMe / 1 Gbps
DNS        A records: ${i.fqdn} and *.${i.fqdn} → this host (wildcard is mandatory: ArNS names resolve as subdomains)
PORTS      80 and 443 forwarded to this host
OS         Ubuntu 24.04: sudo apt install -y podman podman-compose nginx certbot sqlite3 git
TLS        sudo certbot certonly --manual --preferred-challenges dns -d ${i.fqdn} -d '*.${i.fqdn}'
           (wildcard certs need the DNS-01 challenge; they expire every 90 days — automate with your registrar's DNS API)
FILES      mkdir -p ~/ar-io-node/{data,wallets} && cd ~/ar-io-node
           .env                 ← the generated .env from parsec
           compose.yml          ← the generated podman-compose file
           wallets/observer.json← the OBSERVER keypair exported from parsec (chmod 600; the OPERATOR key never goes here)
           /etc/nginx/sites-enabled/${i.fqdn}.conf ← the generated nginx config, then: sudo nginx -t && sudo systemctl reload nginx
FUND       observer wallet ${i.observer}: ~${RECOMMENDED_NODE_WALLET_SOL} SOL (reports); operator ${i.operator}: ≥ ${MIN_OPERATOR_SOL} SOL + the ARIO stake (stays in parsec)
RUN        podman-compose -f compose.yml up -d
           podman generate systemd --new --files --name ar-io-node_core   # optional: boot persistence
CHECK      curl -s https://${i.fqdn}/ar-io/info | jq '{release, wallet, programIds}'   # wallet must equal ${i.operator}, release ≥ 82
           curl -s https://${i.fqdn}/ar-io/healthcheck
           curl -s https://${i.fqdn}/4jBV3ofWh41KhuTs2pFvj-KBZWUkbrbCYlJH0vLA6LM   # → "test"
JOIN       back in parsec: Permaweb Desk → Gateway → Join network (preflight must be all green)
AFTER      https://gateways.ar.io/#/${i.operator}  — observation starts next epoch (24 h). 30 consecutive failed epochs = pruned + slashed.
UPGRADE    podman-compose pull && podman-compose up -d --force-recreate core envoy observer   (never 'down -v')
`;
}

export type ProvisionKit = Record<string, string>;

export function buildProvisionKit(i: NodeEnvInput): ProvisionKit {
  return {
    '.env': generateNodeEnv(i),
    'compose.yml': generatePodmanCompose(),
    [`nginx-${i.fqdn}.conf`]: generateNginx(i.fqdn),
    'CHECKLIST.txt': generateChecklist(i),
  };
}
